language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'CREATE DATABASE funnies_test;' -U postgres
  - cp config/database.example.yml config/database.yml
  - cp config/application.example.yml config/application.yml
script:
  - bundle exec rake
